FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl bash docker-cli docker-cli-compose python3

COPY package.json ./
RUN npm install --production

COPY . .

EXPOSE 8080

CMD ["node", "index.js"]
